networks:
  docker:
    driver: bridge
    external:
      name: docker

volumes:
  db_data:

services:
  db:
    image: postgres:14
    container_name: products-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - docker

  api:
    container_name: products-api
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-micro
    ports:
      - "8082:8080"
    networks:
      - docker